# Generated by Django 6.0.4 on 2026-05-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('vegetarian', models.BooleanField(default=False)),
                ('picture', models.URLField(default='https://www.pngall.com/wp-content/uploads/5/Restaurant-Food-PNG-High-Quality-Image.png', max_length=500)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.restaurant')),
            ],
        ),
    ]
